version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Hub3c.Mentify.sln && dotnet publish ./Hub3c.Mentify.sln -c Debug -o ./obj/Docker/publish"
